server {
  listen 80;
  server_name lightsail.miwupm.es;

  # Let’s Encrypt challenge
  location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
    try_files $uri =404;
    default_type "text/plain";
  }

  # Redirige todo a HTTPS
  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  http2 on;
  server_name lightsail.miwupm.es;

  ssl_certificate     /etc/letsencrypt/live/lightsail.miwupm.es/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/lightsail.miwupm.es/privkey.pem;

  ssl_protocols TLSv1.2 TLSv1.3;

  location / {
    return 200 '{"status":"nginx gateway secure"}';
    add_header Content-Type application/json;
  }
}

