sudo tee /opt/nginx/conf.d/default.conf >/dev/null <<'EOF'
# HTTP
server {
  listen 80;
  server_name lightsail.miwupm.es;

  location = /api-1 { return 301 /api-1/; }

  # Let’s Encrypt challenge
  location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
    try_files $uri =404;
    default_type "text/plain";
  }

  # Redirige todo a HTTPS
  location / { return 301 https://$host$request_uri; }
}

server {
  listen 443 ssl;
  http2 on;
  server_name lightsail.miwupm.es;

  ssl_certificate     /etc/letsencrypt/live/lightsail.miwupm.es/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/lightsail.miwupm.es/privkey.pem;

  ssl_protocols TLSv1.2 TLSv1.3;

  location = /api-1 { return 301 /api-1/; }

  location /api-1/ {
    proxy_pass http://deployed-aws:8080/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    return 200 '{"status":"nginx gateway secure"}';
    add_header Content-Type application/json;
  }
}

EOF

