server {
  listen 80;

  location = /api-1 {
    return 301 /api-1/;
  }

  # Let’s Encrypt HTTP-01 challenge
  location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
    try_files $uri =404;
    default_type "text/plain";
  }

  location /api-1/ {
    proxy_pass http://deployed-aws:8080/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    return 200 '{"status":"nginx gateway up"}';
    add_header Content-Type text/plain;
  }
}
